### ISSUE TITLE
Height animation instead of opacity animation

### ISSUE THREAD

**Issue by colbin8r** [cferdinandi/houdini#34]
Hi Chris--

It is a joy and pleasure to use Kraken and its cousin Keel, as well as the numerous other add-on modules you've created.

I had a question about this one: is it possible to animate the height (or I guess in this case, max-height) property of the element instetad of the opacity? I would prefer to have the content appear by sliding open instead of fading in.

Any thoughts?

Thanks for making all of your code open and available to developers like me!

**Comment by cferdinandi** [comment]
Sigh... this is a big thorn in my side. The short answer is: no. At least, not (easily) with CSS.

The longer answer:

You can animate fixed heights with CSS (ie. `height: 0` to `height: 200px`) with CSS, but `height: auto` cannot be animated. You could try bolting in some sort of JS animation instead, but I wanted to keep things lightweight.

Interesting side note, though: I've found that immediate expansion, while less snazzy looking, feels so much faster than an animation.

Appreciate the kudos, and sorry I don't have a better answer for you on this. I explored this a LOT when I first built Houdini, because I really want to support animations.
