### ISSUE TITLE
Target not focused correctly on accordions

### ISSUE THREAD

**Issue by jerivas** [cferdinandi/houdini#57]
Hi Chris, big fan of your very useful modules here!

I've been used Houdini quite a bit recently and I found a problem with the accordion configuration. To reproduce:
- Create an accordion group with Houdini
- Have a very long (height-wise) collapsible followed by a very short one
- Have some content AFTER the accordion that will always overflow the viewport's height
- Open the first (long) collapsible, all works fine
- Open the second (short) collapsible, you'll end up seeing the content after Houdini (scroll position not set correctly)

Here's a [reduced test case](http://codepen.io/jerivas/pen/QdMzGB). Just click on "Section 2" and you'll end up in the middle of the "Long content after Houdini". Expected result would be to end up seeing the contents of Section 2.

**Comment by cferdinandi** [comment]
Hey, thank you SO much for the reduced test case! Without it, I probably wouldn't have fully grasped what you were describing. 

The reason this happens (as you may have already worked out) is because Houdini doesn't actually change your scrolled position on the page at all. As the second content area is much smaller, and there's content after it, the content gets pushed above the visible viewport.

The focus is correct (in that the element in `:focus` for keyboard navigation purposes is the new content area). Visibility is the problem. 

I *could* address this by adding a function to jump the position on the page, but I think this is better handled by individual developers [using the `callbackOpen` and `callbackClose` setting options](https://github.com/cferdinandi/houdini/#global-settings).

Examples:

- If you have a fixed header you may need to scroll not to the element itself, but to the element PLUS some extra space so it's not obscured by the header. 
- You may wish to animate scrolling to the content with something like [Smooth Scroll](https://github.com/cferdinandi/smooth-scroll) instead of just jumping there.
- Depending on your content structure you may not need to or want to jump to the content at all (think show more/less on YouTube videos, where the link appears after the content instead of before it).

Hope that clears things up!

**Comment by jerivas** [comment]
You're right, callbacks where the way to go. Thanks!

If anyone is interested, here's the little function I created (called at some point on `callbackOnOpen`):

```javascript
function scrollIfNotVisible(element) {
	var windowTop = window.pageYOffset;
	var windowBottom = windowTop + window.innerHeight;
	var top = element.offsetTop;

	if (top < windowTop || top > windowBottom) {
		smoothScroll.animateScroll(element.offsetTop - 100);
	}
}
```
Where the `element` param is the `toggle` received by the callback. The `-100` can be tweaked to the desired offset.

**Comment by cferdinandi** [comment]
Thanks for sharing that for others!
