### ISSUE TITLE
Custom button is wrapped with another button

### ISSUE THREAD

**Issue by colepeters** [cferdinandi/houdini#85]
When using a custom button, I end up with a `<button>` wrapped within another `<button>`. 

My code:
```
  <button data-houdini-toggle='testcase' aria-label='Test case'>
    Test custom button
  </button>
  <div id='testcase' data-houdini-group>
    Test content
  </div>
```

…which outputs:
![image](https://user-images.githubusercontent.com/1713932/63532188-b7a79b80-c4cf-11e9-8be3-7a4f13e55658.png)

Live reproduction: https://codesandbox.io/embed/goofy-ptolemy-4tnuj

Any idea why this is happening, and how to get around it?

Thanks!

**Comment by cferdinandi** [comment]
That sure seems like a bug to me! I'll take a look.

**Comment by colepeters** [comment]
@cferdinandi Whoa, fast! Thanks a bunch!

**Comment by cferdinandi** [comment]
Ok, got it sorted. Custom buttons are not compatible with the accordion feature, because accordions are driven by headings and convey a very specific markup structure.

When using the accordion/group feature, Houdini automatically creates a toggle button and injects it into the heading. But since you're flagging a button as the heading, it's nesting a button in a button.

In other words: not actually a bug, just not working the way you want. And, likely, not well documented on my part. Sorry!

**Comment by colepeters** [comment]
I see, that makes perfect sense. Thanks for looking into this so quickly!
